export const button1 = {
	width: "150px",
	height:'40px',
	padding: "4px",
	borderRadius: "10px",
	border: "1.5px solid #bfa16c",
	background: "#fffbe9",
	color: "#7c5c19",
	fontWeight: 600,
	fontSize: "15px",
	display: "flex",
	alignItems: "center",
	justifyContent: "center",
	gap: "8px",
	boxShadow: "0 2px 8px 0 #bfa16c22",
	cursor: "pointer",
	transition: "box-shadow 0.2s, border-color 0.2s, background 0.2s",
}

export const button2 = {
	width: "150px",
	height:'40px',
	padding: "4px",
	borderRadius: "10px",
	border: "1.5px solid #7b8fa1",
	background: "#f0f6ff",
	color: "#2d3a4a",
	fontWeight: 600,
	fontSize: "14px",
	display: "flex",
	alignItems: "center",
	justifyContent: "center",
	gap: "8px",
	boxShadow: "0 2px 8px 0 #7b8fa122",
	cursor: "pointer",
	transition: "box-shadow 0.2s, border-color 0.2s, background 0.2s",
	marginLeft: "8px"
}